apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-portfolio
  labels:
    {{- include "personal-portfolio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: personal-portfolio
  template:
    metadata:
      labels:
        app: personal-portfolio
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
