apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-portfolio
  labels:
    {{- include "personal-portfolio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: personal-portfolio
  template:
    metadata:
      labels:
        app: personal-portfolio
    spec:
      containers:
{{- if .Values.anubis.enabled }}
        - name: anubis
          image: ghcr.io/techarohq/anubis:latest
          imagePullPolicy: Always
          env:
            - name: "BIND"
              value: ":8080"
            - name: "DIFFICULTY"
              value: "4"
            - name: ED25519_PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: anubis-key
                  key: ED25519_PRIVATE_KEY_HEX
            - name: "METRICS_BIND"
              value: ":9090"
            - name: "SERVE_ROBOTS_TXT"
              value: "true"
            - name: "TARGET"
              value: "http://localhost:80"
            - name: "OG_PASSTHROUGH"
              value: "true"
            - name: "OG_EXPIRY_TIME"
              value: "24h"
          resources:
            limits:
              cpu: 750m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
{{- end }}
        - name: nginx
          image: "{{ .Values.global.image.repository }}{{ .Values.site.image.name }}:{{ .Values.site.image.tag }}"
          ports:
            - containerPort: 80
        - name: proxy-rss
          image: "{{ .Values.global.image.repository }}{{ .Values.proxy_rss.image.name }}:{{ .Values.proxy_rss.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: "RSS_FEED_URL"
              value: "https://blog.wheezy.fr/index.xml"
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecrets }}
