apiVersion: v1
kind: Service
metadata:
  name: personal-portfolio
  labels:
    {{- include "personal-portfolio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
{{- if .Values.anubis.enabled }}
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: anubis
{{- end }}
  selector:
    app: personal-portfolio
