apiVersion: v1
kind: Service
metadata:
  name: personal-portfolio
  labels:
    {{- include "personal-portfolio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: personal-portfolio
