replicaCount: 1
global:
  image:
    repository: ghcr.io/florianspk/personal-portfolio/
    pullSecrets: github-registry

site:
  image:
    name: static-site
    tag: "latest" # Override tag by CI
proxy_rss:
  image:
    name: proxy-rss
    tag: "latest" # Override tag by CI

service:
  type: ClusterIP

ingress:
  enabled: true
  host: florianspk.fr
  ingressClassName: ingress-public

anubis:
  enabled: false
