replicaCount: 1

image:
  repository: ghcr.io/florianspk/personal-portfolio/static-site
  tag: "latest" # Override the default tag
  pullSecrets: github-registry
service:
  type: ClusterIP

ingress:
  enabled: true
  host: florianspk.fr
  ingressClassName: ingress-public
