replicaCount: 1

image:
  repository: ghcr.io/florianspk/personal-portfolio
  tag: "latest" # Override the default tag

service:
  type: ClusterIP

ingress:
  enabled: true
  host: florianspk.fr
  ingressClassName: ingress-public
